# Generated by Django 3.0.8 on 2020-08-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='invite_link',
            field=models.CharField(default='---', max_length=100),
        ),
    ]
